### PR TITLE
feat: US35/36

### PR DESCRIPTION
**Pull request by Gamer92000**

### CODE REVIEW

**Comment by Gamer92000** [comment]
closes #112 #113

**Review by Laennart — CHANGES_REQUESTED** [review]
Looks great so far. Just a UI bug you can see in the screenshot. Also when searching for a name of the user in the invited tab, my browser wants to fill in an email. Maybe a wrong autofill hint?

image

**Review by Laennart — CHANGES_REQUESTED** [review]
Autofill is fixed now but there is still a minor inconvenience:
image

**Review by Laennart — APPROVED** [review]
Awesome! 🏌🏻

**Review by Y4nnikH — APPROVED** [review]
Nice!

**Pull request merged**
